# Generated by Django 3.2.6 on 2021-09-05 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contactmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 5, 20, 27, 42, 683699)),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='msg',
            field=models.TextField(default=''),
        ),
    ]
